# Generated by Django 3.2.10 on 2021-12-28 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaskHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dev_name', models.CharField(max_length=25)),
                ('job_kind', models.CharField(max_length=15)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('pages', models.PositiveSmallIntegerField(max_length=3)),
                ('copies', models.PositiveSmallIntegerField(max_length=3)),
                ('job_number', models.PositiveIntegerField(max_length=10)),
                ('job_name', models.CharField(max_length=32)),
                ('job_result', models.CharField(max_length=15)),
                ('job_result_detail', models.IntegerField(max_length=10)),
            ],
            options={
                'db_table': 'task_history',
            },
        ),
    ]
