# Generated by Django 3.2.10 on 2021-12-30 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobstory', '0002_auto_20211228_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskhistory',
            name='complete_copies',
            field=models.PositiveSmallIntegerField(db_column='complete_copies', null=True, verbose_name='Complete copies'),
        ),
        migrations.AddField(
            model_name='taskhistory',
            name='complete_pages',
            field=models.PositiveSmallIntegerField(db_column='complete_pages', null=True, verbose_name='Complete pages'),
        ),
        migrations.AlterField(
            model_name='taskhistory',
            name='copies',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Copies'),
        ),
        migrations.AlterField(
            model_name='taskhistory',
            name='dev_name',
            field=models.CharField(max_length=25, verbose_name='Device'),
        ),
        migrations.AlterField(
            model_name='taskhistory',
            name='end_time',
            field=models.DateTimeField(verbose_name='End time'),
        ),
        migrations.AlterField(
            model_name='taskhistory',
            name='job_kind',
            field=models.CharField(max_length=15, verbose_name='Job kind'),
        ),
        migrations.AlterField(
            model_name='taskhistory',
            name='job_name',
            field=models.CharField(max_length=32, verbose_name='Job name'),
        ),
        migrations.AlterField(
            model_name='taskhistory',
            name='job_number',
            field=models.PositiveIntegerField(verbose_name='Job number'),
        ),
        migrations.AlterField(
            model_name='taskhistory',
            name='job_result',
            field=models.CharField(max_length=15, verbose_name='Job result'),
        ),
        migrations.AlterField(
            model_name='taskhistory',
            name='job_result_detail',
            field=models.IntegerField(verbose_name='Job result detail'),
        ),
        migrations.AlterField(
            model_name='taskhistory',
            name='pages',
            field=models.PositiveSmallIntegerField(verbose_name='Pages'),
        ),
        migrations.AlterField(
            model_name='taskhistory',
            name='start_time',
            field=models.DateTimeField(verbose_name='Start time'),
        ),
    ]
