# Generated by Django 3.2.10 on 2021-12-30 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobstory', '0003_auto_20211230_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskhistory',
            name='dev_name',
            field=models.CharField(max_length=64, verbose_name='Device'),
        ),
        migrations.AlterField(
            model_name='taskhistory',
            name='job_name',
            field=models.CharField(max_length=64, verbose_name='Job name'),
        ),
    ]
